### PR TITLE
Remove xnft-wrapper proxy -> not necessary with html xnfts anymore

### PR DESCRIPTION
**Pull request by greenish**

### CODE REVIEW

**Comment by armaniferrante** [comment]
Will this break existing xnfts like tiexo?

**Comment by wentokay** [comment]
Would xnfts still be hosted on embed.xnfts.dev? I think this is necessary for including the JWT in requests to .xnfts.dev domains

**Comment by greenish** [comment]
> Will this break existing xnfts like tiexo?

With the new protocol, all entrypoints are html entrypoints so can be loaded directly.

> Would xnfts still be hosted on embed.xnfts.dev? I think this is necessary for including the JWT in requests to .xnfts.dev domains

hm no, xnfts wouldnt be hosted on embed.xnfts.dev anymore.

With the new protocol we can have multi-file xnfts which resolve relative urls. 
These relative urls dont work through the current proxy. Same for "iframe" xnfts with external urls.

so we might need a better proxy that can resolve relative paths as well.

**Comment by armaniferrante** [comment]
You're right. I forgot @callensm had migrated the existing xNFTs.

**Comment by greenish** [comment]
@wentokay this PR adds the userId to the window.xnft.metadata object. Would that remove the need for the jwt in xnfts for you? https://github.com/coral-xyz/backpack/pull/2444

**Pull request merged**
