### PR TITLE
feat: Versioned Transaction

### PR DESCRIPTION
**Pull request by Arrowana**
VersionedTransaction can serialize a Legacy transaction and serialising its message leads to a legacy or v0 message.

It should be quite painless to handle as the interfaces are consuming a base58 string of a serialized transaction in most places.

- [x] Bump web3.js everywhere
- [ ] Understand the untyped xnft thing to see what to change over there
- [ ] Tested at least once for the legacy and V0 transaction message

### CODE REVIEW

**Comment by 0xInq** [comment]
addressed in #1032

**Comment by hkirat** [comment]
@Arrowana implemented some of this in https://github.com/coral-xyz/backpack/pull/1032 . Was able to get a V0 transaction to work. 

Will pause working on it to avoid conflicts. Please let me know if you'd like to finish this. Else I can wrap it up in https://github.com/coral-xyz/backpack/pull/1032

**Comment by hkirat** [comment]
Resuming work on https://github.com/coral-xyz/backpack/pull/1032 since I think I'm almost there.

**Comment by Arrowana** [comment]
Changes are pretty much the same, I see.

@hkirat 
Not sure how you dealt with the balance change, web3.js deserializes the simulation differently so i had to change that.
`Send Legacy V0 Transaction (Devnet)` Let's not confuse legacy and V0, it is already a mess lol

**Comment by hkirat** [comment]
`latest web3.js deserializes the simulation differently so i had to change that.` - Do you mean the changes you've made to the function signatures of `simulateTransaction`  (similar to https://github.com/coral-xyz/backpack/pull/1035/files#diff-e2d20fda1fcc34b68e2e2445d58bc5b675df334ecf7ac1a8e6ea4e630196166aR356) ?
I think I've made the same [here](https://github.com/coral-xyz/backpack/pull/1032/files#diff-e2d20fda1fcc34b68e2e2445d58bc5b675df334ecf7ac1a8e6ea4e630196166aR382) but correct me if you meant something else. 
The response to `simulateTransaction` (SimulatedTransactionResponse) seems like it hasn't been changed.

**Comment by Arrowana** [comment]
> `latest web3.js deserializes the simulation differently so i had to change that.` - Do you mean the changes you've made to the function signatures of `simulateTransaction` (similar to https://github.com/coral-xyz/backpack/pull/1035/files#diff-e2d20fda1fcc34b68e2e2445d58bc5b675df334ecf7ac1a8e6ea4e630196166aR356) ? I think I've made the same [here](https://github.com/coral-xyz/backpack/pull/1032/files#diff-e2d20fda1fcc34b68e2e2445d58bc5b675df334ecf7ac1a8e6ea4e630196166aR382) but correct me if you meant something else. The response to `simulateTransaction` (SimulatedTransactionResponse) seems like it hasn't been changed.

yeah my bad it hasn't changed, i assumed the wrong type from the any at the top somehow

**Pull request closed without merging**
