### PR TITLE
Fix Issue with Accept Friend from Message Screen

### LINKED ISSUE #2522: Accepting a contact request shouldn't show pending banner
Accepting a contact request shows a success toast, but the wrong banner and popover

Screenshot 2023-02-06 at 8 07 17 PM

This banner and dropdown are incorrect if I just accepted a contact request
Screenshot 2023-02-06 at 8 07 30 PM
Screenshot 2023-02-06 at 8 07 41 PM

The profile shows the right contact status

Screenshot 2023-02-06 at 8 08 42 PM

### PR DESCRIPTION
**Pull request by RashulChutani**
This PR closes #2522 

In the `MessageOptions.tsx` and `Banner.tsx`, when the `remoteRequested` variable is true, we make the `areFriends` variable true, when the "Accept Friend" Button is clicked. Here is a workflow video for the same. 

https://user-images.githubusercontent.com/41239718/230927381-18f47605-eb41-4612-b76c-c212b9ece797.mp4

Thanks.

### CODE REVIEW

**Comment by RashulChutani** [comment]
Hi @trucy, Just a gentle reminder to please review this PR. Thanks 🙏

**Comment by RashulChutani** [comment]
Hi @hkirat, A gentle request to please review this PR. I will be extremely thankful. Thanks. 🙏

**Comment by hkirat** [comment]
Hi @RashulChutani , will review it this week

**Comment by RashulChutani** [comment]
Hi @hkirat, Just a gentle reminder to review this PR.

**Comment by RashulChutani** [comment]
Hi @armaniferrante @wentokay Would you mind reviewing this PR, given that @hkirat seems busy? I will be extremely thankful.

**Pull request closed without merging**
