### PR TITLE
Added Resolver for Solana and Ethereum Domain Name Websites.

### PR DESCRIPTION
**Pull request by mjLabrys**
# Solana and Ethereum Name Service Resolver for Backpack.
Solana and Ethereum Domain Name Services (DNS) provide a decentralized and cost-effective way to link domain names to corresponding on-chain data, such as websites associated with those domain names.

This pull request adds support for resolving Solana (SNS) and Ethereum (ENS) domain names in the URL, allowing users to automatically redirect to their website stored in the domain content. The feature build add support for IPFS, IPNS, and regular HTTPS websites, making Backpack a more versatile and desirable crypto wallet. This implementation was greatly inspired from `zhvng`'s [sns-resolver](https://github.com/zhvng/sns-resolver) which was deprecated. 

The new feature integrates with the existing wallet functionality, and utilizes the Solana (Bonfida) and Ethereum (Ethers) library to lookup domain name content and redirect to attached websites upon validation. All invalid URLs will redirect to an error 404 page. Users can also configure the gateway to use of their own choice (including custom url) to resolve their domain website if desired so.

This is probably the first time someone has ever created a domain name website resolver for Solana at the wallet level, and I believe it will greatly enhance the user experience and make Backpack a more powerful tool for the crypto community.

Please review the code and let me know if there are any issues or suggestions for improvements. I would be happy to make any necessary changes to ensure this feature gets merged into the master branch. Thank you!

## Process to Use
1. Set content for SNS or ENS with URL of your desired website. 
    - You can resolve to either IPFS OR IPNS via setting the field to either one of `ipfs=`, `ipns=`, `ipfs://`, `ipns://` respectively. 
    - You can also resolve to a regular `https://` or `http://` website by just setting the field with a regular url if the underlying domain name service supports it. 

2. Assuming Backpack is already installed, go to your URL tab and search for your `<domainName>.sol` or `<domainName>.eth`.
   - It will automatically redirect as well if the search domain is prefixed with `http://` or `https://` such as `http://<domainName>.eth` or postfixed with `/` such as `<domainName>.sol/`.
   - Redirects also work with both SOL and ETH subdomains but it is important to note that:
       -  ENS allows for multiple nested child subdomains which is resolvable by the implementation. Technically, it should be able to resolve infinite(not really) amount of child subdomains. 
       - Bonfida's SNS does NOT allow nested subdomains and so you cannot have a subdomain that owns a subdomain, thus cannot resolve to it. 

## Search Engines
`zhvng` had implemented a way to redirect the browser from searching domain names in the search engine in the address bar since `.sol` or `.eth` is not a recognised domain extension. This new implementation adds support for the most popular search engines `Google`, `DuckDuckGo` and additionally, `Bing`.

### Redirecting SOL or ETH Domain
https://user-images.githubusercontent.com/103424726/214815673-957f7567-9f90-4283-ab7c-7cfb921e0113.mov

### Choosing Different Gateways from the `Preferences` page of Backpack and Redirecting to a ETH Subdomain
https://user-images.githubusercontent.com/103424726/214817943-849b82f0-cad9-43b7-b26c-266e98b7fc40.mov

### CODE REVIEW

**Comment by hkirat** [comment]
@mjLabrys this looks great, could you bring it up to date (there seem to be a few conflicts)?

**Comment by wentokay** [comment]
Love this @mjLabrys! I was wondering if you've tested it in [brave](https://brave.com) and if so does it override, or get overridden by, the native .eth resolver? Thanks!
Screenshot 2023-01-26 at 14 08 14

**Comment by mjLabrys** [comment]
Thanks guys, unfortunately I won't have time to look into both queries until after work but I will make sure to get back to you all.

**Comment by mjLabrys** [comment]
> @mjLabrys this looks great, could you bring it up to date (there seem to be a few conflicts)?

Sorry, I ran into some really weird eslint issues while trying to resolve merge conflicts and refactoring my code which prevented me from committing. Looks like I was working from a severely outdated repository anyway so I just migrated my implementation manually which is now located in a new PR at https://github.com/coral-xyz/backpack/pull/2335.

**Comment by mjLabrys** [comment]
> Love this @mjLabrys! I was wondering if you've tested it in [brave](https://brave.com) and if so does it override, or get overridden by, the native .eth resolver? Thanks! Screenshot 2023-01-26 at 14 08 14

I did test it from Brave, and it overrides its native .eth resolver. We can continue this conversation in this new PR where I migrated everything: https://github.com/coral-xyz/backpack/pull/2335. I ran into some really weird eslint issues while trying to resolve merge conflicts so I manually migrated my implementation into a working, latest repository :p .

**Comment by mjLabrys** [comment]
This PR will be migrated to https://github.com/coral-xyz/backpack/pull/2335.

**Pull request closed without merging**
