### PR TITLE
eslint sort import configuration

### PR DESCRIPTION
**Pull request by tomlinton**
Can run this and merge the results whenever. Will wait for #1023 as it is large.

### CODE REVIEW

**Comment by wentokay** [comment]
oh nice, i _started_ doing some work locally on this earlier with a global eslint config package that'd be shared across the monorepo https://github.com/coral-xyz/backpack/commit/bae4c39bf8645b70d9d17c06f9cf2c039bfac704 as per https://turborepo.org/docs/handbook/linting/eslint

are you happy with these rules now? I could include them in the global config and we could hit everything in one go.. after any big PR merges like you thoughtfully mention!

**Comment by tomlinton** [comment]
Global is even better. Those rules seem to work pretty well, as it groups imports in a sensible kind of way. We might need to exclude the `wallet-standard` package since it is inlined here and we don't want to make it hard to merge future changes.

**Comment by tomlinton** [comment]
Closing this in favour of the global option!

**Comment by wentokay** [comment]
superseded by #1180

**Pull request closed without merging**
