### PR TITLE
Cleaning up some design changes, flickering and missing Scrollbars

### PR DESCRIPTION
**Pull request by greenish**

### CODE REVIEW

**Comment by greenish** [comment]
fixes #1862

**Comment by armaniferrante** [comment]
Additional nit. Padding for the images looks too much still.

Screen Shot 2022-12-15 at 10 15 40 PM
Screen Shot 2022-12-10 at 10 09 00 PM

**Comment by armaniferrante** [comment]
Also fixed https://github.com/coral-xyz/backpack/issues/1863

**Comment by armaniferrante** [comment]
Merging this. Can do the additional nit in a separate change.

**Pull request merged**
