### PR TITLE
Features/helius api for solana history

### PR DESCRIPTION
**Pull request by staccDOTsol**
issue #1794

### CODE REVIEW

**Comment by staccDOTsol** [comment]
Lmk if I should start from scratch and get rid of senseless line edits that were reverted but not quite exactly (I am bad at git)

**Comment by armaniferrante** [comment]
Doesn't load for me.

Screen Shot 2023-01-09 at 5 34 18 PM

**Comment by armaniferrante** [comment]
These changes look like the attached screenshot. Please see the associated issue and figma.

Screen Shot 2023-01-09 at 6 07 06 PM

**Comment by staccDOTsol** [comment]
gm, I'm not all that great at design and ui/ux @armaniferrante maybe we can defer elsewhere - there was some interest by other devs on the issue.

That said, proof is in the pudding, I just spent that last hour trying to slice up the addresses:

**Comment by hkirat** [comment]
Closing in favor of https://github.com/coral-xyz/backpack/pull/2051

**Pull request closed without merging**
