### PR TITLE
Fix xnft address used in `usePreference`

### PR DESCRIPTION
**Pull request by hkirat**
`usePreference` uses the `xnft install address` vs the `xnft address`

### CODE REVIEW

**Comment by jokumusic** [comment]
The recent builds a broken. I've narrowed it down to release 459 which was built with this PR.
This is the error:
image

**Comment by hkirat** [comment]
Thanks for reporting , could you share steps to reproduce?

**Comment by jokumusic** [comment]
Add extension to browser. Go to xnft.gg and try loading an xNFT

**Comment by hkirat** [comment]
By loading you mean previewing ?

**Comment by hkirat** [comment]
Or installing one ?

**Comment by jokumusic** [comment]
Yes, previewing

**Comment by jokumusic** [comment]
It does work on installed ones. I first noticed the issue when testing in simulator. Let me try that.

**Comment by jokumusic** [comment]
Looks like it works on everything but preview

**Pull request merged**
