### PR TITLE
username logout part 1

### PR DESCRIPTION
**Pull request by armaniferrante**
closes https://github.com/coral-xyz/backpack/issues/1694

TODO:

- [x] UI
- [x] Figure out per user JWT switching

### CODE REVIEW

**Comment by tomlinton** [comment]
I think you can skip the JWT user switching. `WithAuth` handles it if the user changes, and the signing prompt will go away when the JWT cache is implemented.

**Comment by armaniferrante** [comment]
Great news @tomlinton

**Comment by armaniferrante** [comment]
Labeling as blocked on the jwt cache.

**Comment by tomlinton** [comment]
JWT cache shouldn't be blocking, it'll work the same way as switching users with the extra signature prompt if its hardware. JWT cache will be merged/finished sometime this weekend though.

**Comment by armaniferrante** [comment]
Going to do cookie deletion in the next pr.

**Pull request merged**
