### PR TITLE
added FileInput

### PR DESCRIPTION
**Pull request by Gajesh2007**
#1441 

- in progress

### CODE REVIEW

**Comment by Gajesh2007** [comment]
yet to test

**Comment by jokumusic** [comment]
I tried to add some updates to your PR, but I don't have permission to. I'm not sure of the right way to do that. 
I added some changes to your PR to get it exported and usable by apps.
I was unable to test, because I think the backpack extension needs to be built with the changes, so that they can be tested. I wasn't able to successfully build the backpack extension to test.

**Comment by hkirat** [comment]
@Gajesh2007 can you merge in the commits from https://github.com/coral-xyz/backpack/pull/1470 in here?

**Comment by armaniferrante** [comment]
How does react native handle file input? Should this be a custom component instead?

**Comment by jokumusic** [comment]
> How does react native handle file input? Should this be a custom component instead?

I was thinking that any of the various react native filepicker components can be rendered. It would be the same for things like drop downs, checkboxes, calendars, etc...

**Pull request closed without merging**
