### PR TITLE
Update icon for recent activity #2122

### PR DESCRIPTION
**Pull request by Anmol567**

### CODE REVIEW

**Comment by callensm** [comment]
can you provide a screenshot of the result that this PR has.

**Comment by Anmol567** [comment]
Attaching the screenshots of result.
Screenshot 1945-01-09 at 9 02 53 PM
Screenshot 1945-01-09 at 9 03 09 PM
Screenshot 1945-01-09 at 9 03 18 PM

**Comment by callensm** [comment]
@Anmol567 can you rebase your branch off the current master please

**Comment by Anmol567** [comment]
Done @callensm

**Pull request merged**
