### PR TITLE
Update collectibles empty state

### PR DESCRIPTION
**Pull request by Merdi-kim**
Here are the results after working on issue #3776. 

Among the provided images, one was a **.jpeg** format so I had to turn it into an SVG file to standardize all the marketplaces icons 
Screenshot 2023-04-25 at 14 49 33
Screenshot 2023-04-25 at 14 49 42

### CODE REVIEW

**Comment by aarongillett** [comment]
This looks good, thanks @Merdi-kim. Two small points:
- can we use the rounded version of the material icon?
- can we make the material icon have a thinner 2px border? This looks like ~4px.

**Comment by Merdi-kim** [comment]
Do you mean the icon above **No collectibles** ??

**Comment by aarongillett** [comment]
> Do you mean the icon above **No collectibles** ??
> 
> Concerning the weight of that icon, I do not think there is a CSS property that can reduce it. Maybe if I can look for a more light icon it could solve. Or simply if I can have access to the same icon in the design that could help a lot @aarongillett

Yes, that’s the icon I meant. You can use the rounded version and adjust the weight of the border using the properties defined [here](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Ainterests%3AFILL%400%3Bwght%40200%3BGRAD%400%3Bopsz%4048). Thanks @Merdi-kim !

**Comment by Merdi-kim** [comment]
@aarongillett  I have made the change to the icon and here is how it looks now 
Screenshot 2023-04-27 at 11 29 39

**Comment by aarongillett** [comment]
Thanks @Merdi-kim . The icon looks better, but still a little dark compared to the mockup. Let’s go with something lighter, like `LIGHT_BORDER_COLOR = "#DFE0E6"` and its dark equivalent (via [colors.ts](https://github.com/coral-xyz/backpack/blob/master/packages/themes/src/colors.ts))

**Comment by Merdi-kim** [comment]
@aarongillett I have just updated the changes you requested me to do. Now here is the result of how the icon looks like 


Screenshot 2023-04-28 at 13 47 34

**Pull request closed without merging**
