### PR TITLE
feat: shorten long  wallet names

### LINKED ISSUE #1989: lack of character overflow for long wallet names
This causes the "1 click copy address" button to disappear 
Screenshot 2023-01-02 at 6 57 02 PM

### PR DESCRIPTION
**Pull request by jim4067**
resolves #1989

Screenshot from 2023-01-17 15-14-40

Screenshot from 2023-01-17 15-14-51

### CODE REVIEW

**Comment by jim4067** [comment]
@hkirat Where could I put a function to shorten long wallet names?

**Comment by wentokay** [comment]
for reference if we needed to do this in react-native [`<Text numberOfLines={1}>`](https://stackoverflow.com/a/36013799) achieves the same effect

**Comment by wentokay** [comment]
> @wentokay, do i need to do this on mobile too?

Thanks for the update @jim4067!

I think web is enough but cc'ing our mobile maestro @peterpme just in case! Peter, do you think we need to add something like https://github.com/coral-xyz/backpack/pull/2116#issuecomment-1385349577 to concat long wallet names in react native?

**Comment by armaniferrante** [comment]
Web is enough for this! We're working on laying the foundation there still.

**Comment by jim4067** [comment]
@wentokay pushed another commit to fix overflow on the `Trusted Sites` pages


Screenshot from 2023-01-18 18-18-06

**Comment by armaniferrante** [comment]
Thank you!

**Pull request merged**
